### ISSUE TITLE
Trim params[:name]

### ISSUE THREAD

**Issue by robinjoseph08** [itsachen/focaccia.life#4]
i believe the reason there are two stewarts is because of trailing whitespace:

![image](https://cloud.githubusercontent.com/assets/2454505/23570013/2f71dc3c-0017-11e7-85fc-fb3bae7d0569.png)

id be happy to put up a pr if youre accepting them!

**Comment by itsachen** [comment]
Yes! This is a bug. I am accepting PRs!
